---
title: "Prac 1"
format: html
editor: visual
---

### Question 1

```{r}
#| message: false
#Reading in dataset into object 
df = airquality

#Find all rows where there are missing values 
findNa = function(df) {
  
  ln = nrow(df)
  
  vec = c()

  
    for (x in 1:ln) {
      if (anyNA(df[x,])) {
      vec = c(vec,x)}
    }
  
  return(vec)
  
}




```

### Question 2

```{r}
#| message: false
#| warning: false

#Mean,sd,min,max of temprature 
df = airquality

mean(df$Temp)
sd(df$Temp)
min(df$Temp)
max(df$Temp)

#Mean,sd,min,max of ozone level 
mean(df$Ozone,na.rm = TRUE)
sd(df$Ozone,na.rm = TRUE)
min(df$Ozone,na.rm = TRUE)
max(df$Ozone,na.rm = TRUE)


```

### Question 3

```{r}
#| warning: false
#Linear Regression 
data = cars


#Assigning x and y values
x = data$speed 
y = data$dist


#Making x a design vector 
x = cbind(1, x)

#Computing beta hat 
beta = solve(t(x)%*%x)%*%t(x)%*%y
print(beta)





```

```{r}
#| warning: false
#Fitting regression model to validate 
lm(data$dist~data$speed)

```

Validated that both betas are the same as finding them using the lm function.
